### ISSUE TITLE
advanced search page - display refinements

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#132]
This page needs to be corrected to match existing production page.

![adv search](https://cloud.githubusercontent.com/assets/3666130/5593846/d065b8ec-91de-11e4-89a9-c29de3ce93be.png)

**Comment by jure** [comment]
Done: 
![image](https://cloud.githubusercontent.com/assets/238667/5614646/5647b11a-94f3-11e4-8e09-230325381705.png)
