### ISSUE TITLE
Template Changes - Search results page

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#134]
II. SEARCH RESULTS PAGE
![1b-almreports-results-spec](https://cloud.githubusercontent.com/assets/3666130/5593855/68c50322-91df-11e4-9544-d39f0f85c81a.png)

Items:
1) The faceted search should be aligned based on the screen shot spec.
2) The Add more articles right hand column has too much space under the Preview List button and needs to be moved up.
3) The Sort by dropdown selection should not be hyperlinked in blue.  It should be displayed black font.  The entire field has a blue border, which should be grey.
4) In the faceted search, there is too much spacing between category title and options returned. Also, close the line type for each single item (ex: PLOS Computational biology wraps but these two lines should have less space than the spacing between journals).

**Comment by jure** [comment]
![image](https://cloud.githubusercontent.com/assets/238667/5611771/fc4fe24a-94ca-11e4-9182-1ba1825c046b.png)

Done. Same as #133, the exact widths and margins are not easily implemented, so they're as close as possible (due to the CSS framework)
