### ISSUE TITLE
Template Changes - Preview List page

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#135]
III. PREVIEW LIST PAGE
![2-almreports-preview-spec](https://cloud.githubusercontent.com/assets/3666130/5593858/790ac672-91df-11e4-9cd1-fdd7847a2aab.png)

The "Review your list of articles" font is incorrect.  Insert more spacing between the "1-25 of 25 articles"  and the Clear all hyperlink.  The Create Report button font stye and size is incorrect and needs to be left aligned.  Please reproduce the same margins on the button as well.

**Comment by jure** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/238667/5611830/2071b17a-94cc-11e4-9736-6464b911263c.png)
