### ISSUE TITLE
Template Changes - Metrics and Visualizations pages

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#136]
IV. METRICS PAGE

![metrics spec](https://cloud.githubusercontent.com/assets/3666130/5594526/51d1e880-9205-11e4-8147-490b0de0be28.png)

*  The border around the Share button needs to be a darker grey.  Also, it needs to be pushed in further left and smaller in size.
*  The font for Downloads needs to be corrected to match production.  It should be pushed down slightly so that the CSV button is top aligned with the first article row.  
*  Each of the articles should be indented on the left 40 px.
*  The article title fonts are too large.  Although they are hyperlinked, they should not displayed in dark grey font. There is too much vertical spacing between article title and article metadata below.
*  The author listing should be a darker shade grey.
*  The article metadata below author listing should be in dark grey with smaller font.  Remove the grey line between author listing and article metadata.
*  "Show all ALMs" font should be smaller.
*  Metrics Data and Article List DOIs on the right hand column should not be in blue font but dark grey.

![metrics2](https://cloud.githubusercontent.com/assets/3666130/5594522/38bc89f4-9205-11e4-908d-2cfb3b65de19.png)

V. VISUALIZATIONS PAGE
![3b-almreports-visualizations-spec](https://cloud.githubusercontent.com/assets/3666130/5593862/a0395920-91df-11e4-8f83-14a7ce9d5ae5.png)

* The graph titles should be shifted moved over 40 px.
* The graph itself should be shifted over to the right of the graph title.
* The Print button should not have a title. The link should be called "Print visualizations" in dark grey font.  Without the title, the link should be moved up higher.
* For the sunburst graph, please use this description text instead:
Sunburst size correlates with total views from [X] articles. Color intensity correlates with Scopus citation count. Clicking on a subject area will zoom into its component subject areas. Clicking the center of the circle will zoom out to a more general view.

**Comment by jure** [comment]
Metrics page done:
![image](https://cloud.githubusercontent.com/assets/238667/5613890/14b1d698-94eb-11e4-9869-1738e5c7186a.png)

**Comment by jure** [comment]
Visualizations page done:
![image](https://cloud.githubusercontent.com/assets/238667/5614315/2728c4e4-94f0-11e4-8aa1-9d8a88e27449.png)

Aligning graphs to the title is tricky, because one would have to dynamically calculate how long the y-axis text/label/number will be and reposition the chart accordingly, i.e. for some it's "100", for some it's "50,000". I don't want to get into this right now, as it's too fiddly, so I made a best guess/prediction alignment, expecting most charts to end up with "50,000" or same order of magnitude max y-axis value.
