### ISSUE TITLE
Error in metrics CSV file download

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#138]
http://test.parascope.io/reports/download_data/68.csv
Error: We're sorry, but something went wrong.

**Comment by jure** [comment]
Did you close it by accident?

**Comment by jenniferlin15** [comment]
not by accident, it's working for me now.
i'll keep an eye on it and reopen if it pops up again.

On Mon, Jan 5, 2015 at 9:53 AM, Jure Triglav <notifications@github.com>
wrote:

> Did you close it by accident?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/articlemetrics/alm-report/issues/138#issuecomment-68746738>
> .
>



-- 
"The blessed will not care what angle they are regarded from,
    Having nothing to hide. Dear, I know nothing of
Either, but when I try to imagine a faultless love
    Or the life to come, what I hear is the murmur
Of underground streams, what I see is a limestone landscape."
- WH Auden

**Comment by jure** [comment]
I can still replicate this bug by clicking on your link, so I'm fixing it. Here's the exception:

```
NoMethodError (undefined method `[]' for nil:NilClass):
  app/models/report_doi.rb:30:in `block in csv_row'
  app/models/report_doi.rb:30:in `csv_row'
  app/models/report_doi.rb:12:in `to_csv'
  app/models/report.rb:104:in `block (2 levels) in to_csv'
  app/models/report.rb:102:in `block in to_csv'
  app/models/report.rb:91:in `to_csv'
  app/controllers/reports_controller.rb:144:in `block (2 levels) in download_data'
  app/controllers/reports_controller.rb:143:in `download_data'
  app/controllers/application_controller.rb:41:in `save_session_dois'
```
