### ISSUE TITLE
Alignment of ALM Reports title and description

### ISSUE THREAD

**Issue by jenniferlin15** [articlemetrics/alm-report#140]
The title and description of ALM Reports (top banner) needs left and right margin padding.  The text on the right is pushing up against the expanded ALM article counter.

![alm reports title](https://cloud.githubusercontent.com/assets/3666130/5617132/25184754-94c0-11e4-95fe-fbba9b7ede8c.png)

**Comment by jure** [comment]
Added margins left and right: 
![image](https://cloud.githubusercontent.com/assets/238667/5618546/530168c6-951a-11e4-8199-17715f08545f.png)

**Comment by jenniferlin15** [comment]
looks perfect!

On Mon, Jan 5, 2015 at 11:36 AM, Jure Triglav <notifications@github.com>
wrote:

> Added margins left and right:
> [image: image]
> <https://cloud.githubusercontent.com/assets/238667/5618546/530168c6-951a-11e4-8199-17715f08545f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/articlemetrics/alm-report/issues/140#issuecomment-68762947>
> .
>



-- 
"The blessed will not care what angle they are regarded from,
    Having nothing to hide. Dear, I know nothing of
Either, but when I try to imagine a faultless love
    Or the life to come, what I hear is the murmur
Of underground streams, what I see is a limestone landscape."
- WH Auden
